version: 2.1

parameters:
  cache_version:
    type: string
    default: "v1"
  aws_ecr_host:
    type: string
    default: "454245708275.dkr.ecr.eu-west-1.amazonaws.com"

#+-----------------------------------------------------------------------------+
#|                               COMMANDS                                      |
#+-----------------------------------------------------------------------------+

commands:
  install_packages:
    steps:
      - run:
          name: Authorize NPM
          command: echo "//registry.npmjs.org/:_authToken=$PRIVATE_NPM_TOKEN" > ~/.npmrc
      - restore_cache:
          key: yarn-cache-<< pipeline.parameters.cache_version >>-{{ checksum "yarn.lock" }}
      - run:
          name: Install node modules
          command: yarn install --pure-lockfile
      - save_cache:
          key: yarn-cache-<< pipeline.parameters.cache_version >>-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.cache/yarn
            - /Users/distiller/Library/Caches/yarn
            - /node_modules

#+-----------------------------------------------------------------------------+
#|                               EXECUTORS                                     |
#+-----------------------------------------------------------------------------+

executors:
  node-14-linux-libc:
    docker:
      - image: << pipeline.parameters.aws_ecr_host >>/rust-node-14-libc-main:latest
  node-14-linux-musl:
    docker:
      - image: << pipeline.parameters.aws_ecr_host >>/rust-node-14-musl-main:latest
  node-16-linux-libc:
    docker:
      - image: << pipeline.parameters.aws_ecr_host >>/rust-node-16-libc-main:latest
  node-16-linux-musl:
    docker:
      - image: << pipeline.parameters.aws_ecr_host >>/rust-node-16-musl-main:latest

#+-----------------------------------------------------------------------------+
#|                                 JOBS                                        |
#+-----------------------------------------------------------------------------+

jobs:
  # test & lint jobs

  test:
    description: << parameters.executor >>
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - install_packages
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Build
          command: |
            #!/bin/bash

            OS=$(uname -o)

            echo -e "\n 🏗️  Running Node v'$NODE_VERSION' build for '$OS'"
            set -e

            export PATH=$PATH:~/.cargo/bin

            # check for MUSL Linux (non-GNU)
            if [ "$OS" = "Linux" ]; then
              CARGO_NET_GIT_FETCH_WITH_CLI=true
              RUSTFLAGS="-C target-feature=-crt-static"
              export RUSTFLAGS
            else # GNU Linux
              CARGO_NET_GIT_FETCH_WITH_CLI=false
            fi

            export CARGO_NET_GIT_FETCH_WITH_CLI

            # build Neon binary for current architecture
            echo -e "\n ⚒️  Building package\n"
            /usr/local/bin/yarn build
      - run:
          name: Test
          command: yarn test --coverage
      - run:
          name: Benchmark
          command: yarn benchmark

#+-----------------------------------------------------------------------------+
#|                                WORKFLOWS                                    |
#+-----------------------------------------------------------------------------+

workflows:
  version: 2

  # run all tests
  test:
    jobs:
      - test:
          context: nuggets
          filters:
            branches:
              ignore:
                - master
          name: "Node BBS+ Signatures: << matrix.executor >>"
          matrix:
            parameters:
              executor: [node-14-linux-libc, node-14-linux-musl, node-16-linux-libc, node-16-linux-musl]
